### ISSUE TITLE
osiris: re-enable `test_eth` and provision some allocation

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/osiris#16]
> After this is complete we should also (in a separate issue) re-enable ETH in Osiris and allocate some ETH to the Osiris wallet.

_Originally posted by @zbuc in https://github.com/penumbra-zone/penumbra/issues/2677#issuecomment-1630901268_

**Comment by zbuc** [comment]
The Osiris address already has some `test_eth` allocated at genesis (https://github.com/penumbra-zone/penumbra/blob/main/testnets/057-ganymede/allocations.csv#L9) so as soon as https://github.com/penumbra-zone/infrastructure/pull/1 is merged/deployed Osiris should be able to put up positions against `test_eth`.
